### PR TITLE
fix(docs): prevent FOUC on website homepage logo

### LINKED ISSUE #4606: New website FOUC
Hi Colin,

Not a Zod issue per se, but I just wanted to share - in case it's unknown - that upon loading the new website, there's sometimes a flash of unstyled content where the Zod icon is briefly displayed full screen. You can see it in these screenshots (I recorded the screen and captured two frames).

I got the issue in Firefox and Chrome.

Hope that helps

Frame X:

Image

Frame X+1:

Image

### PR DESCRIPTION
**Pull request by xabierlameiro**
Fixes #4606

## Summary

Fixed Flash of Unstyled Content (FOUC) issue on the Zod website homepage logo by implementing proper loading states and optimization techniques to prevent the logo from flickering during page load.

**UPDATE**: Also addressed Cumulative Layout Shift (CLS) issue identified by @ByteEVM in PR review for the aside logo on md+ screens.

## Changes

- **Created HeroLogo Component**: New component with loading states, skeleton placeholder, and Next.js Image optimization
- **Enhanced Layout**: Added preload links for critical logo resources to prevent FOUC
- **Updated Homepage**: Replaced direct img tag with optimized HeroLogo component
- **Fixed CLS Issue**: Applied fixed height container (md:h-7) and correct dark mode logo for aside logo on md+ screens

## Technical Implementation

1. **Image Preloading**: Added preload links in layout.tsx for critical logo resources
2. **Loading States**: Implemented opacity transitions and skeleton loading
3. **Next.js Image**: Used optimized Image component with priority loading
4. **Consistent Layout**: Maintained 170px height container to prevent layout shift
5. **Smooth Transitions**: Added CSS animations for better UX
6. **CLS Prevention**: Fixed aside logo container with proper height constraints (md:h-7) and correct LogoWhite usage in dark mode

## Testing

- ✅ Build successful
- ✅ All tests passing: 2732 tests  
- ✅ No regressions introduced
- ✅ Follows project conventions
- ✅ CLS issue resolved on md+ screens

## Before/After

**Before**: 
- Logo briefly appears unstyled causing visual flash during page load
- Aside logo causes layout shift on md+ screens

**After**: 
- Smooth loading with no visual disruption
- Fixed height containers prevent layout shifts
- Proper dark mode logo usage

This fix ensures a professional user experience on the website homepage and navigation while maintaining all existing functionality and responsive behavior.

## Review Feedback Addressed

- ✅ Fixed CLS issue on aside logo for md+ screens (feedback from @ByteEVM)
- ✅ Applied proper fixed height container (md:h-7 instead of md:mb-2)  
- ✅ Corrected dark mode logo to use LogoWhite
- ✅ Removed redundant width classes

### CODE REVIEW

File: packages/docs/components/hero-logo.tsx [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+  return (
+    <div className={`relative ${className || ""}`} style={{ height: "170px" }}>
+      {/* Skeleton/placeholder with the same dimensions */}
+      {!isLoaded && (
+        <div
+          className="absolute inset-0 bg-gray-200 dark:bg-gray-700 rounded-lg animate-pulse flex items-center justify-center"
+          style={{ height: "170px" }}
+        >
+          <div className="w-20 h-20 bg-gray-300 dark:bg-gray-600 rounded-lg opacity-50" />
```
Comment (ByteEVM) [inline packages/docs/components/hero-logo.tsx]: Sizing could be minified:
```suggestion
          <div className="size-20 bg-gray-300 dark:bg-gray-600 rounded-lg opacity-50" />
```

Comment (xabierlameiro) [reply packages/docs/components/hero-logo.tsx]: Thanks! Applied in the latest commit.

**Comment by ByteEVM** [comment]
Nice changes! One last suggestion from my end;

I've noticed a layout shift (CLS) with the aside's logo (_the one right above version selector_),
you can notice this in `md` (768px) or larger screen sizes.

Tested with latest Vercel deployment on cache bypass

**Comment by xabierlameiro** [comment]
> Nice changes! One last suggestion from my end;
> 
> I've noticed a layout shift (CLS) with the aside's logo (_the one right above version selector_), you can notice this in `md` (768px) or larger screen sizes.
> 
> Tested with latest Vercel deployment on cache bypass

Great catch @ByteEVM! Just fixed the aside logo layout shift by creating an optimized component with Next.js Image and proper sizing. Should eliminate the CLS you observed on md+ screens. 

Please test when the new deployment is ready! 🚀

File: packages/docs/components/sidebar-logo.tsx [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+import Image from "next/image";
+import { useState } from "react";
+
+interface SidebarLogoProps {
+  src: string;
+  alt: string;
+  width?: number;
+  height?: number;
+  className?: string;
+}
```
Comment (ByteEVM) [inline packages/docs/components/sidebar-logo.tsx]: This interface isn't needed, as `ImageProps` exists

```suggestion
import Image, { type ImageProps } from "next/image";
import { useState } from "react";
```

File: packages/docs/components/sidebar-logo.tsx [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+
+export function SidebarLogo({ src, alt, width = 24, height = 24, className = "h-5" }: SidebarLogoProps) {
```
Comment (ByteEVM) [inline packages/docs/components/sidebar-logo.tsx]: Following the import suggestion, change with `ImageProps`
```suggestion
export function SidebarLogo({ src, alt, width = 24, height = 24, className = "h-5" }: ImageProps) {
```

**Review by ByteEVM — CHANGES_REQUESTED** [review]

**Comment by ByteEVM** [comment]
> > Nice changes! One last suggestion from my end;
> > I've noticed a layout shift (CLS) with the aside's logo (_the one right above version selector_), you can notice this in `md` (768px) or larger screen sizes.
> > Tested with latest Vercel deployment on cache bypass
> 
> Great catch @ByteEVM! Just fixed the aside logo layout shift by creating an optimized component with Next.js Image and proper sizing. Should eliminate the CLS you observed on md+ screens.
> 
> Please test when the new deployment is ready! 🚀

Actually, it's still there. Looks like you've modified the logo within the version selector, not the one right above it.

I've implemented the changes, at `app/layout.config.tsx`

I'm fixing the height at `md`+
— also re-imported dark version of the logo:

```diff
- // import LogoWhite from "@/public/logo/logo-white.png";
+ import LogoWhite from "@/public/logo/logo-white.png";

-   <div className="md:mb-2">
-    <Image alt="Zod logo" src={Logo} sizes="100px" className="hidden dark:block w-8 md:w-8" aria-label="Zod logo" />
-     <Image alt="Zod logo" src={Logo} sizes="100px" className="block dark:hidden w-8 md:w-8" aria-label="Zod logo" />

+   <div className="md:mb-1 md:h-7">
+     <Image alt="Zod logo" src={LogoWhite} sizes="100px" className="hidden dark:block w-8" aria-label="Zod logo" />
+     <Image alt="Zod logo" src={Logo} sizes="100px" className="block dark:hidden w-8" aria-label="Zod logo" />
```

**Comment by ByteEVM** [comment]
`SidebarLogo` looks stretched;
`<` left is Vercel deployment, `>` right is production:

zod

Can't test right now, but a fix could likely be `aspect-square`?
Also, I don't think a `SidebarLogo` component is needed at all, as the shift in layout caused by the lack of space within the selector is horizontal (horizontal shifts aren't _that bad I guess?_)

**Comment by colinhacks** [comment]
Thanks this is great!
