### PR TITLE
fix: rewrite $constructor to be compatible with Hermes

### LINKED ISSUE #4148: v4: Error - "Cannot call a class as a function" in React Native.
Building a schema with zod v4 (for example simply `const str = z.string()`, any schema construction method will cause the error) in an Expo project throws a "Cannot call a class as a function" error. 

I was able to confirm a minimal repro by using `npx create-expo-app@latest`, adding zod v4, and adding the above string parse line to the home component function body, and nothing else. 

There's no indication of deeper error source. No linter error occurs, and it's such a basic functionality that I know works in other environments I suspect something fishy is happening with the Metro bundling process and the $constructor function from @zod/core.

### PR DESCRIPTION
**Pull request by gdorsi**
fixes #4148

This PR fixes the compat issues with Hermes by using a function as a class wrapper in $constructor

Tested with the repro provided in https://github.com/colinhacks/zod/pull/4466

EDIT: We are using this fork in [jazz](https://github.com/garden-co/jazz) and can confirm that it solved our issues with React Native

## Summary by CodeRabbit

- **Refactor**
  - Improved the internal initialization and construction process for certain components, resulting in a more modular and streamlined structure. No changes to the public interface or user-facing functionality.

### CODE REVIEW

File: packages/zod/src/v4/core/core.ts [hunk 1]
```diff
@@ -14,42 +14,52 @@ export /*@__NO_SIDE_EFFECTS__*/ function $constructor<T extends ZodTrait, D = T[
...
-      return inst?._zod?.traits?.has(name);
+  const Parent = params?.Parent ?? Object;
+  class Definition extends Parent {}
+
+  function _(this: any, def: D) {
+    if (params?.Parent) {
+      return construct(new Definition(), def);
     }
+
+    return construct(this, def);
```
Comment (gdorsi) [inline packages/zod/src/v4/core/core.ts:53]: Using the if here to reuse the instance when the parent is not defined.

Can be simplified in doing always `return construct(new Definition(), def);` didn't perf-test the difference honestly.

**Comment by colinhacks** [comment]
Landed in zod@beta, can you try & report back?

**Comment by rdnsan** [comment]
> Landed in zod@beta, can you try & report back?

it works for me. using `zod@3.25.24-beta.0`

**Comment by colinhacks** [comment]
Landed in stable: `zod@3.25.24`
