### PR TITLE
fix: apply description and default metadata to enum, const, and not schemas in fromJSONSchema

### LINKED ISSUE #5732: `z.fromJSONSchema()` does not support metadata for enums, literals and not/never
Related to #5564 (closed by #5586)

While for the simple cases metadata parsing was added, they do not seem to be parsed for all of the special cases in `convertBaseSchema`, such as enums and literals.

```ts
// Will equal { description: "The name of the person" }
const stringMeta = z.fromJSONSchema({
  type: "string",
  description: "The name of the person",
}).meta();

// But all of these will be undefined
const enumMeta = z.fromJSONSchema({
  type: "string",
  enum: ["red", "green", "blue"],
  description: "The color of the object",
}).meta();
const literalMeta = z.fromJSONSchema({
  type: "string",
  const: "hello",
  description: "A constant string value",
}).meta();
const notMeta = z.fromJSONSchema({
  description: "Placeholder item",
  not: {},
}).meta();
```

### PR DESCRIPTION
**Pull request by mibragimov**
## Problem

`z.fromJSONSchema()` ignores `description` and `default` fields when the JSON Schema uses `enum`, `const`, or `not: {}` (never). This happens because these paths use early returns in `convertBaseSchema()` before reaching the metadata application block at the bottom of the function.

**Minimal reproduction:**
```ts
const schema = z.fromJSONSchema({
  enum: ["red", "green", "blue"],
  description: "A color value",
  default: "red",
});

schema.description; // undefined ❌ (expected "A color value")
schema.parse(undefined); // throws ❌ (expected "red")
```

Fixes #5732

## Solution

Extract the metadata application (description + default) into a helper function `applyBaseMetadata()` and call it from each of the affected early-return paths:

- `not: {}` → `z.never()`
- `enum` → `z.enum()` / `z.literal()` / `z.union()`
- `const` → `z.literal()`

## Tests

Added five new tests covering:
- `description` on enum schema
- `description` on const schema
- `description` on not: {} (never) schema
- `default` on enum schema
- `default` on const schema

### CODE REVIEW

File: packages/zod/src/v4/classic/from-json-schema.ts [hunk 1]
```diff
@@ -586,26 +578,32 @@ function convertSchema(schema: JSONSchema.JSONSchema | boolean, ctx: ConversionC
     baseSchema = z.readonly(baseSchema);
   }
 
-  // Collect metadata: core schema keywords and unrecognized keys
+  // Apply `default` so it wraps the fully-composed schema. This ensures
```
Comment (tmpho079-pixel) [inline packages/zod/src/v4/classic/from-json-schema.ts:581]: import os
from datetime import date
from enum import Enum

from pydantic import BaseModel, Field

from xai_sdk import Client
from xai_sdk.chat import system, user

# Pydantic Schemas

class Currency(str, Enum):
    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"

class LineItem(BaseModel):
    description: str = Field(description="Description of the item or service")
    quantity: int = Field(description="Number of units", ge=1)
    unit_price: float = Field(description="Price per unit", ge=0)

class Address(BaseModel):
    street: str = Field(description="Street address")
    city: str = Field(description="City")
    postal_code: str = Field(description="Postal/ZIP code")
    country: str = Field(description="Country")

class Invoice(BaseModel):
    vendor_name: str = Field(description="Name of the vendor")
    vendor_address: Address = Field(description="Vendor's address")
    invoice_number: str = Field(description="Unique invoice identifier")
    invoice_date: date = Field(description="Date the invoice was issued")
    line_items: list[LineItem] = Field(description="List of purchased items/services")
    total_amount: float = Field(description="Total amount due", ge=0)
    currency: Currency = Field(description="Currency of the invoice")

client = Client(api_key=os.getenv("XAI_API_KEY"))
chat = client.chat.create(model="grok-4.20-reasoning")

chat.append(system("Given a raw invoice, carefully analyze the text and extract the invoice data into JSON format."))
chat.append(
user("""
Vendor: Acme Corp, 123 Main St, Springfield, IL 62704
Invoice Number: INV-2025-001
Date: 2025-02-10
Items: - Widget A, 5 units, $10.00 each - Widget B, 2 units, $15.00 each
Total: $80.00 USD
""")
)

# The parse method returns a tuple of the full response object as well as the parsed pydantic object.

response, invoice = chat.parse(Invoice)
assert isinstance(invoice, Invoice)

# Can access fields of the parsed invoice object directly

print(invoice.vendor_name)
print(invoice.invoice_number)
print(invoice.invoice_date)
print(invoice.line_items)
print(invoice.total_amount)
print(invoice.currency)

# Can also access fields from the raw response object such as the content.

# In this case, the content is the JSON schema representation of the parsed invoice object

print(response.content)

**Review by tmpho079-pixel — APPROVED** [review]

**Review by tmpho079-pixel — APPROVED** [review]

**Comment by colinhacks** [comment]
Merged. Pushed a small follow-up on top: rather than calling `applyBaseMetadata` from each early-return branch in `fromJSONSchema`, I consolidated `description` and `default` application into a single site at the end of `convertSchema`, after composition keywords and wrappers run. Same fix for `enum`, `const`, and `not`, and it picks up the latent bug on the `type: [...]` array path for free. Thanks for tracking this one down 👍

_Note: this comment was produced by an AI coding assistant._

**Comment by colinhacks** [comment]
Landed in Zod 4.4
